
def tours():
  print("\t\t\tTours(Decameron Explore)")
  print()
  print("-Santuario Nacional Manglares de Tumbes")
  print("\tAdulto-->98USD Niño-->98USD")
  print()
  print("-Manglares de Puerto Pizarro.")
  print("\tAdulto-->68USD Niño-->68USD")
  print()
  print("-Pesca de Altura")
  print("\tAdulto-->203USD Niño-->N/A")
  print()
  print("-Paseo Costero Marino")
  print("\tAdulto-->69USD Niño-->69USD")
  print()
  print("-Observacion de Ballenas(Agosto-Octubre)")
  print("\tAdulto-->69USD Niño-->69USD")
  print()
  print("-Sunset Tour Privado")
  print("\tAdulto-->106USD Niño-->106USD")
  print()
  print("-Adicional Sunset Tour")
  print("\tAdulto-->51USD Niño-->51USD")
  print()
  print("-La Ruta Hemingway Terrestre.")
  print("\tAdulto-->47USD Niño-->47USD")
  print()
  print("-Tour Mancora.")
  print("\tAdulto-->19USD Niño-->19USD")
  print()
  print("-Snorkeling con Tortugas")
  print("\tAdulto-->69USD Niño-->69USD")
  print()
  print("-Bubble Marker(120 minutos)")
  print("\tAdulto-->N/A Niño-->47USD")
  print()
  print("-Discover Scuba Diving Piscina(60 minutos)")
  print("\tAdulto-->71USD Niño-->71USD")
  print()
  print("-Discover Scuba Diving Mar(1 inmersión)")
  print("\tAdulto-->154USD Niño-->154USD")
  print()
  print("-Open Water Diver(3 días)")
  print("\tAdulto-->505USD Niño-->N/A")
  print()
  print("-Advanced Open Water(2.5 dias)")
  print("\tAdulto-->402USD Niño-->N/A")
  print()
  print("-Dos Inmerciones Recreativas Playa")
  print("\tAdulto-->178USD Niño-->N/A")
  print()
  print("-Dos Inmerciones Recreativas Bote")
  print("\tAdulto-->192USD Niño-->N/A")
  print()
  print("-Paseo en bote")
  print("\tAdulto-->48USD Niño-->48USD")

