def promociones():
  print("\t\t\tPromociones")
  print()
  print("Promocion 1: Persona por Noche")
  print("\t\tPRECIO")
  print("\t\t317soles(92USD)")
  print()
  print("\t\tVigencia")
  print()
  print("\t\tPara Compra: Desde el 1 de enero de 2016")
  print("\t\tPara Viaje: Hasta el 24 de diciembre 2016 (Solo en temporada baja)")
  print()
  print("\t\tTemporadas")
  print()
  print("\t\tTEMPORADA BAJA 2016")
  print("\t\tTemporadas sujetas a cambio sin previo aviso.")
  print("\t\tDel 27 de Marzo al 27 de Julio")
  print("\t\tDel 31 de julio al 01 de Agosto")
  print("\t\tDel 19 de Agosto al 02 de Octubre")
  print("\t\tDel 16 de Octubre al 24 de Diciembre")
  print("\t\tINCLUYE")
  print("\t\tAlojamiento en confortables habitaciones")
  print("\t\tDesayunos, almuerzos y cenas buffet")
  print("\t\tCenas a la Carta")
  print("\t\tAperitivos diarios y nocturnos")
  print("\t\tBebidas alcohólicas y no alcohólicas nacionales e internacionales ilimitadas")
  print("\t\tPrograma de actividades diarias")
  print("\t\tDeportes acuáticos no motorizados (Windsurf, kayak, botes de pedal, snorkeling, y veleros)")
  print("\t\tToallas de playa en el Centro de Actividades")
  print("\t\tEntretenimiento nocturno (shows para niños y adultos)")
  print("\t\tNO INCLUYE")
  print("\t\tProductos o servicios no especificados en el programa")
  print("\t\tCondiciones CONDICIONES Y RESTRICCIONES")
  print("\t\tTarifas en acomodación doble/triple en habitación estándar con vista al jardín entre semana, para estadías de mínimo 2 noches")
  print("\t\tTarifa aplica en noches de domingo a jueves")
  print("\t\tPodrían aplicar suplementos por tipo de habitación y fin de semana")
  print("\t\tAplica únicamente para temporada baja")
  print("\t\tConsultar por tarifas aplicables en temporada media y alta o feriados")
  print("\t\tAplica para pagos en efectivo o con tarjetas de crédito")
  print("\t\tTipo de cambio referencial S/. 3.45")
  print("\t\tTARIFAS EXPRESADAS EN DÓLARES AMERICANOS Y NUEVOS SOLES")
  print("\t\tNO COMBINABLE CON OTRAS PROMOCIONES")
  print("\t\tEn caso de grupos, favor cotizar de acuerdo a disponibilidad")
  print("\t\tOtras condiciones podrían aplicar")

