def menuprincipal():
    print("\tPrograma de Organizacion de Hotel Royal Decameron Punta Sal")
    print("\t1 --> Inicio.")
    print("\t2 --> Reservaciones.")
    print("\t3 --> Eventos.")
    print("\t4 --> Tours.")
    print("\t5 --> Promociones.")
    print("\t6 --> Descripcion de Habitaciones.")
    print("\t7 --> Restaurantes.")
def menuinicio():
    print("1--->Ubicacion.")
    print("2--->Programa Todo Incluido.")
    print("3--->Descripcion de Habitaciones.")
    print("4--->Servicios.")
    print()
    x=int(input("Ingrese la opcion que desea observar: "))
    if x==1:
        print()
        print("El Hotel Royal Decameron Punta Sal está ubicado en el kilómetro 1190 de la Carretera Panamericana Norte, cerca de la frontera sur de Ecuador, distrito de Zorritos, región de Tumbes, Perú. La ciudad de Tumbes se encuentra a 1 hora 30 minutos en avión de la ciudad de Lima y el hotel a su vez está ubicado a 1 hora 15 minutos del aeropuerto de Tumbes por tierra. El Hotel Royal Decameron Punta Sal Beach Resort, Spa & Convention Center cuenta con 1 kilómetro y medio de playa. La zona goza de sol durante todo el año. Sus aguas son cálidas, sobrepasando generalmente los 20ºC. También cuenta con una gran diversidad biológica por su ubicación en esta zona al extremo norte del Perú, en donde el agua de la corriente de Humboldt por lo general no tiene influencia directa, las condiciones microclimáticas que presenta durante todas las estaciones del año, de tipo tropical, con cielo despejado, sol radiante, temperaturas cálidas del aire y del mar")
    if x==2:
        print()
        print("El Hotel cuenta con todas los servicios y las instalaciones que usted necesita: ")
        print()
        print("* Desayunos, almuerzos y cenas tipo buffet.")
        print("* Cenas a la carta.")
        print("* Snack y piqueos.")
        print("* Estacion de cevicheria durante el almuerzo.")
        print("* Bebidas alcoholicas nacionales e internacionales.")
        print("* Refrescos ilimitados.")
        print("* Deportes nauticos no motorizados.")
        print("* Piscina para adultos.")
        print("* Sillas y toallas para la palya y piscina.")
        print("* Gimnasio.")
        print("* Sala de Videojuegos.")
        print("* Dos canchas de tenis.")
        print("* Torneo de voley y futbol playa.")
        print("* Programacion de actividades diarias.")
        print("* Entretenimiento nocturno.")
        print("* Discoteca.")
        print("* Topico o Enfermeria.")
        print()
    if x==3:
        print()
        print("Contamos con 313 habitaciones (42 habitaciones superior twin, 12 bungalows y 259 habitaciones estándar) que cuentan con: ")
        print()
        print("* Con una cama King Size o dos camas Twin Size.")
        print("* Sofa camam adicional.")
        print("* Aire acondicionado.")
        print("* Television por cable.")
        print("* Secador de cabello.")
        print("* Agua caliente.")
        print("* Telefono.")
        print("* Terraza o balcon.")
        print()
    if x==4:
        print()
        print("---> Nuestro Hotel cuenta con 3 Restaurantes: ")
        print()
        print("* Buffet principal:            - RESTAURANTE BLUE MARLIN.")
        print("                                 Desayuno, almuerzo y cenas tematicas.")
        print()
        print("* Dos restaurantes a la carta: - RESTAURANTE LA CEVICHERIA.")
        print("                                 Especialidad: Comida peruana.")
        print("                               - RESTAURANTE OLIVA LIMON.")
        print("                                 Especialidad: Comida mediterranea.")
        print()
        print("* Snack:                       - RESTAURANTE BLUE MARLIN / RESTAURANTE OLIVA LIMON.")
        
        print()
        print("---> Nuestro hotel cuenta con 5 bares fijos: ")
        print()
        print("* Lobby Bar.")
        print("* Bar del Sol (piscina).")
        print("* Discoteca.")
        print("* Restaurante Oliva Limon.")
        print("* Restaurante La Cevicheria.")
        print("* Centro de convenciones.")
        print("* Restaurante Blue Marlin.")
        print()

        print("---> Otros servicion con cargo adicional.")
        print()
        print("* Salon de convenciones con capacidad para 500 personas.")
        print("* Decameron Explorer Tour Desk ofreciendo mas de 17 excursiones y circuitos a diferentes puntos de interes en Perú.")
        print("* Llamadas locales e internacionales.")
        print("* Boutique.")
        print("* Lavanderia.")
        print("* Wi-fi.")
        print("* SPA.")
        print("* Asistencia medica.")
        print("* Cajilla de seguridad.")


